FROM ruby:2.7.1
COPY apt.conf /etc/apt/apt.conf
RUN bundle config --global frozen 1
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD COPY Gemfile /usr/src/app/
ONBUILD COPY Gemfile.lock /usr/src/app/
ONBUILD RUN bundle install

ONBUILD COPY . /usr/src/app
RUN apt update
RUN apt install -y nodejs
RUN apt update
RUN apt install -y postgresql postgresql-contrib
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/11/main/pg_hba.conf
RUN echo "local   all       all   trust" >> /etc/postgresql/11/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/11/main/postgresql.conf
EXPOSE 5432
RUN pg_ctlcluster 11 main start
#RUN su postgres
#RUN psql  -U postgres -c "CREATE DATABASE oms_api_development"
#RUN psql -h localhost  -U postgres -c "CREATE DATABASE oms_api_development"


EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
