FROM ruby:2.3
COPY apt.conf /etc/apt/apt.conf
RUN apt-get update -qq \
&& apt-get install -y nodejs postgresql-client
ADD . /Rails-Docker
WORKDIR /Rails-Docker
RUN gem update --system
#RUN bundle install
#RUN gem install bundler:2.2.26
RUN gem install bundler
RUN gem install rails
EXPOSE 3000
COPY . ./
EXPOSE 3000
ENTRYPOINT ["./entrypoints/docker-entrypoint.sh"]
CMD ["rails", "server", "-b", "0.0.0.0"]
